-- Generic in-app notifications, first used for: "a trip matching your
-- registered vehicle capacity is available, here's what you'd be paid."
--
-- Writes only ever happen through create_trip_notification() below: the
-- AI_backend Python service calls Supabase with the anon key and has no
-- authenticated session for the logistics provider it's notifying, so a
-- direct insert would be rejected by RLS -- same reasoning as create_order()
-- in the orders migration. Reads and "mark as read" updates, by contrast,
-- happen from the logistics provider's own authenticated browser session,
-- so those are plain RLS-protected table access, no RPC needed.
create table public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index notifications_recipient_idx on public.notifications(recipient_id, created_at desc);

alter table public.notifications enable row level security;

create policy "Recipients can view their own notifications"
  on public.notifications for select
  using (auth.uid() = recipient_id);

create policy "Recipients can mark their own notifications read"
  on public.notifications for update
  using (auth.uid() = recipient_id)
  with check (auth.uid() = recipient_id);

create or replace function public.create_trip_notification(
  p_recipient_id uuid,
  p_type text,
  p_title text,
  p_body text,
  p_payload jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  insert into public.notifications (recipient_id, type, title, body, payload)
  values (p_recipient_id, p_type, p_title, p_body, coalesce(p_payload, '{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.create_trip_notification(uuid, text, text, text, jsonb) to anon, authenticated;
