-- Farmer-set price alerts ("notify me when Tomato goes above/below X/kg"),
-- checked opportunistically: there's no scheduler in this stack, so
-- check_price_alerts() runs as a side effect of /api/price-trend whenever
-- anyone requests that commodity's price (see AI_backend/main.py). This
-- means an alert can sit past its threshold for a while before anyone
-- happens to ask about that commodity -- acceptable for a demo, not a
-- substitute for a real background job.
create table public.price_alerts (
  id bigint generated by default as identity primary key,
  farmer_id uuid not null references public.farmers(profile_id) on delete cascade,
  commodity text not null,
  threshold_price numeric(10, 2) not null check (threshold_price > 0),
  direction text not null check (direction in ('above', 'below')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index price_alerts_commodity_active_idx on public.price_alerts(commodity, active);

alter table public.price_alerts enable row level security;

create policy "Farmers can view their own price alerts"
  on public.price_alerts for select
  using (auth.uid() = farmer_id);

create policy "Farmers can create their own price alerts"
  on public.price_alerts for insert
  with check (auth.uid() = farmer_id);

create policy "Farmers can update their own price alerts"
  on public.price_alerts for update
  using (auth.uid() = farmer_id)
  with check (auth.uid() = farmer_id);

create policy "Farmers can delete their own price alerts"
  on public.price_alerts for delete
  using (auth.uid() = farmer_id);

-- Called by the AI backend (anon key, no auth.uid() of its own) so this has
-- to be security definer, same reasoning as create_trip_notification().
create or replace function public.check_price_alerts(p_commodity text, p_current_price numeric)
returns integer
language plpgsql
security definer set search_path = public
as $$
declare
  v_alert record;
  v_count integer := 0;
begin
  for v_alert in
    select * from public.price_alerts
    where commodity = p_commodity
      and active
      and (
        (direction = 'above' and p_current_price >= threshold_price)
        or (direction = 'below' and p_current_price <= threshold_price)
      )
  loop
    insert into public.notifications (recipient_id, type, title, body, payload)
    values (
      v_alert.farmer_id,
      'price_alert',
      p_commodity || ' price alert',
      p_commodity || ' is now Rs.' || p_current_price || '/kg, ' || v_alert.direction ||
        ' your target of Rs.' || v_alert.threshold_price || '/kg.',
      jsonb_build_object(
        'commodity', p_commodity, 'current_price', p_current_price,
        'threshold_price', v_alert.threshold_price, 'direction', v_alert.direction
      )
    );
    update public.price_alerts set active = false where id = v_alert.id;
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

grant execute on function public.check_price_alerts(text, numeric) to anon, authenticated;
