alter table public.logistics_providers
  add column if not exists service_type text;

create table if not exists public.fleet_vehicles (
  id bigint generated by default as identity primary key,
  logistics_provider_id uuid not null references public.logistics_providers(profile_id) on delete cascade,
  vehicle_type text not null,
  registration_number text,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fleet_vehicles_provider_idx on public.fleet_vehicles(logistics_provider_id);

alter table public.fleet_vehicles enable row level security;

create policy "Logistics providers can view their own fleet"
  on public.fleet_vehicles for select
  using (auth.uid() = logistics_provider_id);

create policy "Logistics providers can add their own fleet"
  on public.fleet_vehicles for insert
  with check (auth.uid() = logistics_provider_id);

create policy "Logistics providers can update their own fleet"
  on public.fleet_vehicles for update
  using (auth.uid() = logistics_provider_id);

create policy "Logistics providers can delete their own fleet"
  on public.fleet_vehicles for delete
  using (auth.uid() = logistics_provider_id);
