-- Farmer pincode (needed to resolve real farm -> buyer distance for routing;
-- buyers already have one, farmers only had free-text crop_location).
alter table public.farmer_profiles
  add column if not exists pincode text;

-- ---------------------------------------------------------------------------
-- Orders: a buyer's confirmed purchase. One order can be sourced from
-- MULTIPLE farmers (order_allocations) and shipped as multiple vehicle trips
-- (order_trips), matching the multi-farmer routing model in the AI backend.
-- ---------------------------------------------------------------------------
create table public.orders (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null references public.bulk_buyers(profile_id) on delete cascade,
  commodity text not null,
  market text,
  order_demand_kg numeric(14, 2) not null check (order_demand_kg > 0),
  base_price_per_kg numeric(14, 2),
  market_crop_price_per_kg numeric(14, 2),
  logistics_cost_total numeric(14, 2),
  platform_commission_total numeric(14, 2),
  final_price_per_kg numeric(14, 2),
  grand_total numeric(14, 2),
  status text not null default 'confirmed' check (status in ('confirmed', 'fulfilled', 'cancelled')),
  breakdown jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index orders_buyer_id_idx on public.orders(buyer_id);

create table public.order_allocations (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  farmer_id uuid not null references public.farmers(profile_id) on delete cascade,
  crop_id bigint references public.crop_details(id) on delete set null,
  allocated_kg numeric(14, 2) not null check (allocated_kg > 0),
  farmer_payout numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index order_allocations_order_id_idx on public.order_allocations(order_id);
create index order_allocations_farmer_id_idx on public.order_allocations(farmer_id);

create table public.order_trips (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  vehicle_class text,
  total_weight_kg numeric(14, 2),
  distance_km numeric(14, 2),
  cost numeric(14, 2),
  stops jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index order_trips_order_id_idx on public.order_trips(order_id);

alter table public.orders enable row level security;
alter table public.order_allocations enable row level security;
alter table public.order_trips enable row level security;

create policy "Buyers can view their own orders" on public.orders for select using (auth.uid() = buyer_id);
create policy "Buyers can create their own orders" on public.orders for insert with check (auth.uid() = buyer_id);
create policy "Farmers can view orders they contributed to" on public.orders for select
  using (exists (select 1 from public.order_allocations oa where oa.order_id = orders.id and oa.farmer_id = auth.uid()));

create policy "Farmers can view their own allocations" on public.order_allocations for select using (auth.uid() = farmer_id);
create policy "Buyers can view allocations for their own orders" on public.order_allocations for select
  using (exists (select 1 from public.orders o where o.id = order_allocations.order_id and o.buyer_id = auth.uid()));

create policy "Buyers can view trips for their own orders" on public.order_trips for select
  using (exists (select 1 from public.orders o where o.id = order_trips.order_id and o.buyer_id = auth.uid()));
create policy "Farmers can view trips for orders they contributed to" on public.order_trips for select
  using (exists (
    select 1 from public.order_allocations oa
    where oa.order_id = order_trips.order_id and oa.farmer_id = auth.uid()
  ));

-- ---------------------------------------------------------------------------
-- create_order(): the AI backend calls Supabase with the anon key (same as
-- commodity_supply_kg), so it never has an authenticated auth.uid() -- a
-- plain insert would be rejected by the RLS policies above. This
-- security-definer function is the one privileged write path: it takes an
-- explicit buyer_id (trusted from the backend, no separate auth layer exists
-- yet) plus the allocation/trip arrays as jsonb, and inserts all three rows
-- in one call so an order is never left half-written.
-- ---------------------------------------------------------------------------
create or replace function public.create_order(
  p_buyer_id uuid,
  p_commodity text,
  p_market text,
  p_order_demand_kg numeric,
  p_base_price_per_kg numeric,
  p_market_crop_price_per_kg numeric,
  p_logistics_cost_total numeric,
  p_platform_commission_total numeric,
  p_final_price_per_kg numeric,
  p_grand_total numeric,
  p_breakdown jsonb,
  p_allocations jsonb,   -- [{farmer_id, crop_id, allocated_kg, farmer_payout}, ...]
  p_trips jsonb          -- [{vehicle_class, total_weight_kg, distance_km, cost, stops}, ...]
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id bigint;
  alloc jsonb;
  trip jsonb;
begin
  insert into public.orders (
    buyer_id, commodity, market, order_demand_kg, base_price_per_kg,
    market_crop_price_per_kg, logistics_cost_total, platform_commission_total,
    final_price_per_kg, grand_total, breakdown
  ) values (
    p_buyer_id, p_commodity, p_market, p_order_demand_kg, p_base_price_per_kg,
    p_market_crop_price_per_kg, p_logistics_cost_total, p_platform_commission_total,
    p_final_price_per_kg, p_grand_total, p_breakdown
  ) returning id into new_order_id;

  for alloc in select * from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb)) loop
    insert into public.order_allocations (order_id, farmer_id, crop_id, allocated_kg, farmer_payout)
    values (
      new_order_id,
      (alloc->>'farmer_id')::uuid,
      nullif(alloc->>'crop_id', '')::bigint,
      (alloc->>'allocated_kg')::numeric,
      coalesce((alloc->>'farmer_payout')::numeric, 0)
    );
  end loop;

  for trip in select * from jsonb_array_elements(coalesce(p_trips, '[]'::jsonb)) loop
    insert into public.order_trips (order_id, vehicle_class, total_weight_kg, distance_km, cost, stops)
    values (
      new_order_id,
      trip->>'vehicle_class',
      (trip->>'total_weight_kg')::numeric,
      (trip->>'distance_km')::numeric,
      (trip->>'cost')::numeric,
      coalesce(trip->'stops', '[]'::jsonb)
    );
  end loop;

  return new_order_id;
end;
$$;

grant execute on function public.create_order(
  uuid, text, text, numeric, numeric, numeric, numeric, numeric, numeric, numeric, jsonb, jsonb, jsonb
) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- commodity_supply_listings(): per-farmer supply rows (not just the
-- aggregate commodity_supply_kg total) so the backend can allocate a buyer's
-- order across specific farmers and resolve each one's pincode for routing.
-- Exposes only farmer_id (a uuid, not identifying on its own), crop_id,
-- available quantity, and pincode -- never name/aadhaar/bank details.
-- ---------------------------------------------------------------------------
create or replace function public.commodity_supply_listings(p_crop_type text)
returns table (
  farmer_id uuid,
  crop_id bigint,
  available_kg numeric,
  pincode text
)
language sql
security definer
set search_path = public
stable
as $$
  select
    cd.farmer_id,
    cd.id as crop_id,
    (case when cd.harvested then cd.turnover else cd.expected_turnover end) * 100 as available_kg,
    fp.pincode
  from public.crop_details cd
  join public.farmer_profiles fp on fp.farmer_id = cd.farmer_id
  where lower(cd.crop_type) = lower(p_crop_type)
    and coalesce(case when cd.harvested then cd.turnover else cd.expected_turnover end, 0) > 0
    and fp.pincode is not null and fp.pincode <> '';
$$;

grant execute on function public.commodity_supply_listings(text) to anon, authenticated;
